allcards_data=
{"cards":[
{"id":"Cellar","box":"base","type":"Action","cost":"2"},
{"id":"Chapel","box":"base","type":"Action","cost":"2"},
{"id":"Moat","box":"base","type":"Action,Reaction","cost":"2"},
{"id":"Chancellor","box":"base","type":"Action","cost":"3"},
{"id":"Village","box":"base","type":"Action","cost":"3"},
{"id":"Woodcutter","box":"base","type":"Action","cost":"3"},
{"id":"Workshop","box":"base","type":"Action","cost":"3"},
{"id":"Bureaucrat","box":"base","type":"Action,Attack","cost":"4"},
{"id":"Feast","box":"base","type":"Action","cost":"4"},
{"id":"Gardens","box":"base","type":"Victory","cost":"4"},
{"id":"Militia","box":"base","type":"Action,Attack","cost":"4"},
{"id":"Moneylender","box":"base","type":"Action","cost":"4"},
{"id":"Remodel","box":"base","type":"Action","cost":"4"},
{"id":"Smithy","box":"base","type":"Action","cost":"4"},
{"id":"Spy","box":"base","type":"Action,Attack","cost":"4"},
{"id":"Thief","box":"base","type":"Action,Attack","cost":"4"},
{"id":"Throne Room","box":"base","type":"Action","cost":"4"},
{"id":"Council Room","box":"base","type":"Action","cost":"5"},
{"id":"Festival","box":"base","type":"Action","cost":"5"},
{"id":"Laboratory","box":"base","type":"Action","cost":"5"},
{"id":"Library","box":"base","type":"Action","cost":"5"},
{"id":"Market","box":"base","type":"Action","cost":"5"},
{"id":"Mine","box":"base","type":"Action","cost":"5"},
{"id":"Witch","box":"base","type":"Action,Attack","cost":"5"},
{"id":"Adventurer","box":"base","type":"Action","cost":"6"},
{"id":"Courtyard","box":"intrigue","type":"Action","cost":"2"},
{"id":"Pawn","box":"intrigue","type":"Action","cost":"2"},
{"id":"Secret Chamber","box":"intrigue","type":"Action,Reaction","cost":"2"},
{"id":"Great Hall","box":"intrigue","type":"Action,Victory","cost":"3"},
{"id":"Masquerade","box":"intrigue","type":"Action","cost":"3"},
{"id":"Shanty Town","box":"intrigue","type":"Action","cost":"3"},
{"id":"Steward","box":"intrigue","type":"Action","cost":"3"},
{"id":"Swindler","box":"intrigue","type":"Action,Attack","cost":"3"},
{"id":"Wishing Well","box":"intrigue","type":"Action","cost":"3"},
{"id":"Baron","box":"intrigue","type":"Action","cost":"4"},
{"id":"Bridge","box":"intrigue","type":"Action","cost":"4"},
{"id":"Conspirator","box":"intrigue","type":"Action","cost":"4"},
{"id":"Coppersmith","box":"intrigue","type":"Action","cost":"4"},
{"id":"Ironworks","box":"intrigue","type":"Action","cost":"4"},
{"id":"Mining Village","box":"intrigue","type":"Action","cost":"4"},
{"id":"Scout","box":"intrigue","type":"Action","cost":"4"},
{"id":"Duke","box":"intrigue","type":"Victory","cost":"5"},
{"id":"Minion","box":"intrigue","type":"Action,Attack","cost":"5"},
{"id":"Saboteur","box":"intrigue","type":"Action,Attack","cost":"5"},
{"id":"Torturer","box":"intrigue","type":"Action,Attack","cost":"5"},
{"id":"Trading Post","box":"intrigue","type":"Action","cost":"5"},
{"id":"Tribute","box":"intrigue","type":"Action","cost":"5"},
{"id":"Upgrade","box":"intrigue","type":"Action","cost":"5"},
{"id":"Harem","box":"intrigue","type":"Treasure,Victory","cost":"6"},
{"id":"Nobles","box":"intrigue","type":"Action,Victory","cost":"6"},
{"id":"Embargo","box":"seaside","type":"Action","cost":"2","requires":["Embargo tokens"]},
{"id":"Haven","box":"seaside","type":"Action,Duration","cost":"2"},
{"id":"Lighthouse","box":"seaside","type":"Action,Duration","cost":"2"},
{"id":"Native Village","box":"seaside","type":"Action","cost":"2","requires":["Native Village mats"]},
{"id":"Pearl Diver","box":"seaside","type":"Action","cost":"2"},
{"id":"Ambassador","box":"seaside","type":"Action,Attack","cost":"3"},
{"id":"Fishing Village","box":"seaside","type":"Action,Duration","cost":"3"},
{"id":"Lookout","box":"seaside","type":"Action","cost":"3"},
{"id":"Smugglers","box":"seaside","type":"Action","cost":"3"},
{"id":"Warehouse","box":"seaside","type":"Action","cost":"3"},
{"id":"Caravan","box":"seaside","type":"Action,Duration","cost":"4"},
{"id":"Cutpurse","box":"seaside","type":"Action,Attack","cost":"4"},
{"id":"Island","box":"seaside","type":"Action,Victory","cost":"4","requires":["Island mats"]},
{"id":"Navigator","box":"seaside","type":"Action","cost":"4"},
{"id":"Pirate Ship","box":"seaside","type":"Action,Attack","cost":"4","requires":["Pirate Ship mats","Coins"]},
{"id":"Salvager","box":"seaside","type":"Action","cost":"4"},
{"id":"Sea Hag","box":"seaside","type":"Action,Attack","cost":"4"},
{"id":"Treasure Map","box":"seaside","type":"Action","cost":"4"},
{"id":"Bazaar","box":"seaside","type":"Action","cost":"5"},
{"id":"Explorer","box":"seaside","type":"Action","cost":"5"},
{"id":"Ghost Ship","box":"seaside","type":"Action,Attack","cost":"5"},
{"id":"Merchant Ship","box":"seaside","type":"Action,Duration","cost":"5"},
{"id":"Outpost","box":"seaside","type":"Action,Duration","cost":"5"},
{"id":"Tactician","box":"seaside","type":"Action,Duration","cost":"5"},
{"id":"Treasury","box":"seaside","type":"Action","cost":"5"},
{"id":"Wharf","box":"seaside","type":"Action,Duration","cost":"5"},
{"id":"Island mats","box":"seaside","special":true},
{"id":"Pirate Ship mats","box":"seaside","special":true},
{"id":"Native Village mats","box":"seaside","special":true},
{"id":"Embargo tokens","box":"seaside","special":true},
{"id":"Coins","box":"seaside","special":true},
{"id":"Potion","box":"alchemy","type":"Treasure,Special","cost":"4","special":true},
{"id":"Herbalist","box":"alchemy","type":"Action","cost":"2"},
{"id":"Apprentice","box":"alchemy","type":"Action","cost":"5"},
{"id":"Transmute","box":"alchemy","type":"Action","cost":"0P"},
{"id":"Vineyard","box":"alchemy","type":"Victory","cost":"0P"},
{"id":"Apothecary","box":"alchemy","type":"Action","cost":"2P"},
{"id":"Scrying Pool","box":"alchemy","type":"Action,Attack","cost":"2P"},
{"id":"University","box":"alchemy","type":"Action","cost":"2P"},
{"id":"Alchemist","box":"alchemy","type":"Action","cost":"3P"},
{"id":"Familiar","box":"alchemy","type":"Action,Attack","cost":"3P"},
{"id":"Philosopher's Stone","box":"alchemy","type":"Treasure","cost":"3P"},
{"id":"Golem","box":"alchemy","type":"Action","cost":"4P"},
{"id":"Possession","box":"alchemy","type":"Action","cost":"6P"},
{"id":"Trade Route mat","name":"Trade Route mat & coins","box":"prosperity","special":true},
{"id":"Victory Point tokens","name":"Victory Point mats & tokens","box":"prosperity","special":true},
{"id":"Platinum","box":"prosperity","type":"Treasure,Special","cost":"9","special":true},
{"id":"Colony","box":"prosperity","type":"Victory,Special","cost":"11","special":true},
{"id":"Loan","box":"prosperity","type":"Treasure","cost":"3"},
{"id":"Trade Route","box":"prosperity","type":"Action","cost":"3","requires":["Trade Route mat"]},
{"id":"Watchtower","box":"prosperity","type":"Action,Reaction","cost":"3"},
{"id":"Bishop","box":"prosperity","type":"Action","cost":"4","requires":["Victory Point tokens"]},
{"id":"Monument","box":"prosperity","type":"Action","cost":"4","requires":["Victory Point tokens"]},
{"id":"Quarry","box":"prosperity","type":"Treasure","cost":"4"},
{"id":"Talisman","box":"prosperity","type":"Treasure","cost":"4"},
{"id":"Worker's Village","box":"prosperity","type":"Action","cost":"4"},
{"id":"City","box":"prosperity","type":"Action","cost":"5"},
{"id":"Contraband","box":"prosperity","type":"Treasure","cost":"5"},
{"id":"Counting House","box":"prosperity","type":"Action","cost":"5"},
{"id":"Mint","box":"prosperity","type":"Action","cost":"5"},
{"id":"Mountebank","box":"prosperity","type":"Action,Attack","cost":"5"},
{"id":"Rabble","box":"prosperity","type":"Action,Attack","cost":"5"},
{"id":"Royal Seal","box":"prosperity","type":"Treasure","cost":"5"},
{"id":"Vault","box":"prosperity","type":"Action","cost":"5"},
{"id":"Venture","box":"prosperity","type":"Treasure","cost":"5"},
{"id":"Goons","box":"prosperity","type":"Action,Attack","cost":"6","requires":["Victory Point tokens"]},
{"id":"Grand Market","box":"prosperity","type":"Action","cost":"6"},
{"id":"Hoard","box":"prosperity","type":"Treasure","cost":"6"},
{"id":"Bank","box":"prosperity","type":"Treasure","cost":"7"},
{"id":"Expand","box":"prosperity","type":"Action","cost":"7"},
{"id":"Forge","box":"prosperity","type":"Action","cost":"7"},
{"id":"King's Court","box":"prosperity","type":"Action","cost":"7"},
{"id":"Peddler","box":"prosperity","type":"Action","cost":"8"},
{"id":"Prize","name":"Prize cards","box":"cornucopia","special":true},
{"id":"Hamlet","box":"cornucopia","type":"Action","cost":"2"},
{"id":"Fortune Teller","box":"cornucopia","type":"Action,Attack","cost":"3"},
{"id":"Menagerie","box":"cornucopia","type":"Action","cost":"3"},
{"id":"Farming Village","box":"cornucopia","type":"Action","cost":"4"},
{"id":"Horse Traders","box":"cornucopia","type":"Action,Reaction","cost":"4"},
{"id":"Remake","box":"cornucopia","type":"Action","cost":"4"},
{"id":"Tournament","box":"cornucopia","type":"Action","cost":"4","requires":["Prize"]},
{"id":"Young Witch","box":"cornucopia","type":"Action,Attack","cost":"4"},
{"id":"Harvest","box":"cornucopia","type":"Action","cost":"5"},
{"id":"Horn of Plenty","box":"cornucopia","type":"Treasure","cost":"5"},
{"id":"Hunting Party","box":"cornucopia","type":"Action","cost":"5"},
{"id":"Jester","box":"cornucopia","type":"Action,Attack","cost":"5"},
{"id":"Fairgrounds","box":"cornucopia","type":"Victory","cost":"6"},
{"id":"Crossroads","box":"hinterlands","type":"Action","cost":"2"},
{"id":"Duchess","box":"hinterlands","type":"Action","cost":"2"},
{"id":"Fool's Gold","box":"hinterlands","type":"Treasure,Reaction","cost":"2"},
{"id":"Develop","box":"hinterlands","type":"Action","cost":"3"},
{"id":"Oasis","box":"hinterlands","type":"Action","cost":"3"},
{"id":"Oracle","box":"hinterlands","type":"Action,Attack","cost":"3"},
{"id":"Scheme","box":"hinterlands","type":"Action","cost":"3"},
{"id":"Tunnel","box":"hinterlands","type":"Victory,Reaction","cost":"3"},
{"id":"Jack of All Trades","box":"hinterlands","type":"Action","cost":"4"},
{"id":"Noble Brigand","box":"hinterlands","type":"Action,Attack","cost":"4"},
{"id":"Nomad Camp","box":"hinterlands","type":"Action","cost":"4"},
{"id":"Silk Road","box":"hinterlands","type":"Victory","cost":"4"},
{"id":"Spice Merchant","box":"hinterlands","type":"Action","cost":"4"},
{"id":"Trader","box":"hinterlands","type":"Action,Reaction","cost":"4"},
{"id":"Cache","box":"hinterlands","type":"Treasure","cost":"5"},
{"id":"Cartographer","box":"hinterlands","type":"Action","cost":"5"},
{"id":"Embassy","box":"hinterlands","type":"Action","cost":"5"},
{"id":"Haggler","box":"hinterlands","type":"Action","cost":"5"},
{"id":"Highway","box":"hinterlands","type":"Action","cost":"5"},
{"id":"Ill-Gotten Gains","box":"hinterlands","type":"Treasure","cost":"5"},
{"id":"Inn","box":"hinterlands","type":"Action","cost":"5"},
{"id":"Mandarin","box":"hinterlands","type":"Action","cost":"5"},
{"id":"Margrave","box":"hinterlands","type":"Action,Attack","cost":"5"},
{"id":"Stables","box":"hinterlands","type":"Action","cost":"5"},
{"id":"Border Village","box":"hinterlands","type":"Action","cost":"6"},
{"id":"Farmland","box":"hinterlands","type":"Victory","cost":"6"},
{"id":"Poor House","box":"darkages","type":"Action","cost":"1"},
{"id":"Beggar","box":"darkages","type":"Action,Reaction","cost":"2"},
{"id":"Squire","box":"darkages","type":"Action","cost":"2"},
{"id":"Vagrant","box":"darkages","type":"Action","cost":"2"},
{"id":"Forager","box":"darkages","type":"Action","cost":"3"},
{"id":"Hermit","box":"darkages","type":"Action","cost":"3","requires":["Madman"]},
{"id":"Market Square","box":"darkages","type":"Action,Reaction","cost":"3"},
{"id":"Sage","box":"darkages","type":"Action","cost":"3"},
{"id":"Storeroom","box":"darkages","type":"Action","cost":"3"},
{"id":"Urchin","box":"darkages","type":"Action,Attack","cost":"3","requires":["Mercenary"]},
{"id":"Armory","box":"darkages","type":"Action","cost":"4"},
{"id":"Death Cart","box":"darkages","type":"Action,Looter","cost":"4"},
{"id":"Feodum","box":"darkages","type":"Victory","cost":"4"},
{"id":"Fortress","box":"darkages","type":"Action","cost":"4"},
{"id":"Ironmonger","box":"darkages","type":"Action","cost":"4"},
{"id":"Marauder","box":"darkages","type":"Action,Attack,Looter","cost":"4","requires":["Spoils"]},
{"id":"Procession","box":"darkages","type":"Action","cost":"4"},
{"id":"Rats","box":"darkages","type":"Action","cost":"4"},
{"id":"Scavenger","box":"darkages","type":"Action","cost":"4"},
{"id":"Wandering Minstrel","box":"darkages","type":"Action","cost":"4"},
{"id":"Band of Misfits","box":"darkages","type":"Action","cost":"5"},
{"id":"Bandit Camp","box":"darkages","type":"Action","cost":"5","requires":["Spoils"]},
{"id":"Catacombs","box":"darkages","type":"Action","cost":"5"},
{"id":"Count","box":"darkages","type":"Action","cost":"5"},
{"id":"Counterfeit","box":"darkages","type":"Treasure","cost":"5"},
{"id":"Cultist","box":"darkages","type":"Action,Attack,Looter","cost":"5"},
{"id":"Graverobber","box":"darkages","type":"Action","cost":"5"},
{"id":"Junk Dealer","box":"darkages","type":"Action","cost":"5"},
{"id":"Mystic","box":"darkages","type":"Action","cost":"5"},
{"id":"Pillage","box":"darkages","type":"Action,Attack","cost":"5","requires":["Spoils"]},
{"id":"Rebuild","box":"darkages","type":"Action","cost":"5"},
{"id":"Rogue","box":"darkages","type":"Action,Attack","cost":"5"},
{"id":"Altar","box":"darkages","type":"Action","cost":"6"},
{"id":"Hunting Grounds","box":"darkages","type":"Action","cost":"6"},
{"id":"Knights","box":"darkages","type":"Action,Attack,Knight","cost":"5"},
{"id":"Shelters","box":"darkages","type":"Special","cost":"0","special":true},
{"id":"Ruins","box":"darkages","type":"Special","cost":"0","special":true},
{"id":"Spoils","box":"darkages","special":true},
{"id":"Madman","box":"darkages","special":true},
{"id":"Mercenary","box":"darkages","special":true},
{"id":"Plaza","box":"guilds","type":"Action","cost":"4","requires":["Coin Tokens"]},
{"id":"Baker","box":"guilds","type":"Action","cost":"5","requires":["Coin Tokens"]},
{"id":"Candlestick Maker","box":"guilds","type":"Action","cost":"2","requires":["Coin Tokens"]},
{"id":"Merchant Guild","box":"guilds","type":"Action","cost":"5","requires":["Coin Tokens"]},
{"id":"Masterpiece","box":"guilds","type":"Treasure","cost":"3"},
{"id":"Stonemason","box":"guilds","type":"Action","cost":"2"},
{"id":"Soothsayer","box":"guilds","type":"Action,Attack","cost":"5"},
{"id":"Advisor","box":"guilds","type":"Action","cost":"4"},
{"id":"Taxman","box":"guilds","type":"Action,Attack","cost":"4"},
{"id":"Doctor","box":"guilds","type":"Action","cost":"3"},
{"id":"Journeyman","box":"guilds","type":"Action","cost":"5"},
{"id":"Butcher","box":"guilds","type":"Action","cost":"5","requires":["Coin Tokens"]},
{"id":"Herald","box":"guilds","type":"Action","cost":"4"},
{"id":"Coin Tokens","name":"Coin Tokens","box":"guilds","special":true},
{"id":"Distant Lands","box":"adventures","type":"Action,Reserve,Victory","cost":"5","requires":["Tavern Mat"]},
{"id":"Port","box":"adventures","type":"Action","cost":"4"},
{"id":"Coin of the Realm","box":"adventures","type":"Treasure,Reserve","cost":"2","requires":["Tavern Mat"]},
{"id":"Page","box":"adventures","type":"Action,Traveller","cost":"2","requires":["Page Upgrades"]},
{"id":"Peasant","box":"adventures","type":"Action,Traveller","cost":"2","requires":["Peasant Upgrades","+1 Card Token","+1 Action Token","+1 Buy Token","+1 Coin Token","Tavern Mat"]},
{"id":"Ratcatcher","box":"adventures","type":"Action,Reserve","cost":"2","requires":["Tavern Mat"]},
{"id":"Raze","box":"adventures","type":"Action","cost":"2"},
{"id":"Amulet","box":"adventures","type":"Action,Duration","cost":"3"},
{"id":"Caravan Guard","box":"adventures","type":"Action,Duration,Reaction","cost":"3"},
{"id":"Dungeon","box":"adventures","type":"Action,Duration","cost":"3"},
{"id":"Gear","box":"adventures","type":"Action,Duration","cost":"3"},
{"id":"Guide","box":"adventures","type":"Action,Reserve","cost":"3","requires":["Tavern Mat"]},
{"id":"Duplicate","box":"adventures","type":"Action,Reserve","cost":"4","requires":["Tavern Mat"]},
{"id":"Magpie","box":"adventures","type":"Action","cost":"4"},
{"id":"Messenger","box":"adventures","type":"Action","cost":"4"},
{"id":"Miser","box":"adventures","type":"Action","cost":"4","requires":["Tavern Mat"]},
{"id":"Ranger","box":"adventures","type":"Action","cost":"4","requires":["Journey Token"]},
{"id":"Transmogrify","box":"adventures","type":"Action,Reserve","cost":"4","requires":["Tavern Mat"]},
{"id":"Artificer","box":"adventures","type":"Action","cost":"5"},
{"id":"Bridge Troll","box":"adventures","type":"Action,Attack,Duration","cost":"5","requires":["-1 Coin Token"]},
{"id":"Giant","box":"adventures","type":"Action,Attack","cost":"5","requires":["Journey Token"]},
{"id":"Haunted Woods","box":"adventures","type":"Action,Attack,Duration","cost":"5"},
{"id":"Lost City","box":"adventures","type":"Action","cost":"5"},
{"id":"Relic","box":"adventures","type":"Treasure,Attack","cost":"5","requires":["-1 Card Token"]},
{"id":"Royal Carriage","box":"adventures","type":"Action,Reserve","cost":"5","requires":["Tavern Mat"]},
{"id":"Storyteller","box":"adventures","type":"Action","cost":"5"},
{"id":"Swamp Hag","box":"adventures","type":"Action,Attack,Duration","cost":"5"},
{"id":"Treasure Trove","box":"adventures","type":"Treasure","cost":"5"},
{"id":"Wine Merchant","box":"adventures","type":"Action,Reserve","cost":"5","requires":["Tavern Mat"]},
{"id":"Hireling","box":"adventures","type":"Action,Duration","cost":"6"},
{"id":"Page Upgrades","box":"adventures","special":true},
{"id":"Peasant Upgrades","box":"adventures","special":true},
{"id":"Tavern Mat","box":"adventures","special":true},
{"id":"-1 Coin Token","box":"adventures","special":true},
{"id":"-1 Card Token","box":"adventures","special":true},
{"id":"Journey Token","box":"adventures","special":true},
{"id":"Estate Token","box":"adventures","special":true},
{"id":"Trashing Token","box":"adventures","special":true},
{"id":"+1 Action Token","box":"adventures","special":true},
{"id":"+1 Buy Token","box":"adventures","special":true},
{"id":"+1 Card Token","box":"adventures","special":true},
{"id":"+1 Coin Token","box":"adventures","special":true},
{"id":"-2 Cost Token","box":"adventures","special":true},
{"id":"Alms","box":"adventures","event":true,"cost":"0"},
{"id":"Ball","box":"adventures","event":true,"cost":"5","requires":["-1 Coin Token"]},
{"id":"Bonfire","box":"adventures","event":true,"cost":"3"},
{"id":"Borrow","box":"adventures","event":true,"cost":"0","requires":["-1 Card Token"]},
{"id":"Expedition","box":"adventures","event":true,"cost":"3"},
{"id":"Ferry","box":"adventures","event":true,"cost":"3","requires":["-2 Cost Token"]},
{"id":"Inheritance","box":"adventures","event":true,"cost":"7","requires":["Estate Token"]},
{"id":"Lost Arts","box":"adventures","event":true,"cost":"6","requires":["+1 Action Token"]},
{"id":"Mission","box":"adventures","event":true,"cost":"4"},
{"id":"Pathfinding","box":"adventures","event":true,"cost":"8","requires":["+1 Card Token"]},
{"id":"Pilgrimage","box":"adventures","event":true,"cost":"4","requires":["Journey Token"]},
{"id":"Plan","box":"adventures","event":true,"cost":"3","requires":["Trashing Token"]},
{"id":"Quest","box":"adventures","event":true,"cost":"0"},
{"id":"Raid","box":"adventures","event":true,"cost":"5","requires":["-1 Card Token"]},
{"id":"Save","box":"adventures","event":true,"cost":"1"},
{"id":"Scouting Party","box":"adventures","event":true,"cost":"2"},
{"id":"Seaway","box":"adventures","event":true,"cost":"5","requires":["+1 Buy Token"]},
{"id":"Trade","box":"adventures","event":true,"cost":"5"},
{"id":"Training","box":"adventures","event":true,"cost":"6","requires":["+1 Coin Token"]},
{"id":"Travelling Fair","box":"adventures","event":true,"cost":"2"},
{"id":"VP tokens","name":"Victory Point Tokens","box":"empires","special":true},
{"id":"Debt Tokens","box":"empires","special":true},
{"id":"Archive","box":"empires","type":"Action,Duration","cost":"5"},
{"id":"Capital","box":"empires","type":"Treasure","cost":"5","requires":["Debt Tokens"]},
{"id":"Chariot Race","box":"empires","type":"Action","cost":"3","requires":["VP tokens"]},
{"id":"Charm","box":"empires","type":"Treasure","cost":"5"},
{"id":"City Quarter","box":"empires","type":"Action","cost":"0d8","requires":["Debt Tokens"]},// cost 0 coins, 8 debt
{"id":"Crown","box":"empires","type":"Action,Treasure","cost":"5"},
{"id":"Enchantress","box":"empires","type":"Action,Attack,Duration","cost":"3"},
{"id":"Engineer","box":"empires","type":"Action","cost":"0d4","requires":["Debt Tokens"]},// cost 0 coins, 4 debt
{"id":"Farmers' Market","box":"empires","type":"Action,Gathering","cost":"3","requires":["VP tokens"]},
{"id":"Forum","box":"empires","type":"Action","cost":"5"},
{"id":"Groundskeeper","box":"empires","type":"Action","cost":"5","requires":["VP tokens"]},
{"id":"Legionary","box":"empires","type":"Action,Attack","cost":"5"},
{"id":"Royal Blacksmith","box":"empires","type":"Action","cost":"0d8","requires":["Debt Tokens"]},// cost 0 coins, 8 debt
{"id":"Overlord","box":"empires","type":"Action","cost":"0d8","requires":["Debt Tokens"]},// cost 0 coins, 8 debt
{"id":"Sacrifice","box":"empires","type":"Action","cost":"4","requires":["VP tokens"]},
{"id":"Temple","box":"empires","type":"Action,Gathering","cost":"4","requires":["VP tokens"]},
{"id":"Villa","box":"empires","type":"Action","cost":"4"},
{"id":"Wild Hunt","box":"empires","type":"Action,Gathering","cost":"5","requires":["VP tokens"]},
{"id":"Encampment/Plunder","box":"empires","type":"Action","cost":"2","requires":["VP tokens"]},// Plunder costs 5, type treasure, uses VP tokens
{"id":"Patrician/Emporium","box":"empires","type":"Action","cost":"2","requires":["VP tokens"]},// Emporium costs 5, uses VP tokens
{"id":"Settlers/Bustling Village","box":"empires","type":"Action","cost":"2"},// Bustling Village costs 5
{"id":"Castles","box":"empires","type":"Victory,Castle","cost":"3","requires":["VP tokens"]},// costs range from 3-10, types include: Treasure,Action
{"id":"Catapult/Rocks","box":"empires","type":"Action,Attack","cost":"3"},// Rocks costs 4, is a treasure
{"id":"Gladiator/Fortune","box":"empires","type":"Action","cost":"3","requires":["Debt Tokens"]},// Fortune costs 8 coins, 8 debt, type treasure
{"id":"Advance","box":"empires","event":true,"cost":"0"},
{"id":"Annex","box":"empires","event":true,"cost":"0d8","requires":["Debt Tokens"]},// costs 0 coins, 8 debt
{"id":"Banquet","box":"empires","event":true,"cost":"3"},
{"id":"Conquest","box":"empires","event":true,"cost":"6","requires":["VP tokens"]},
{"id":"Delve","box":"empires","event":true,"cost":"2"},
{"id":"Dominate","box":"empires","event":true,"cost":"14","requires":["VP tokens"]},
{"id":"Donate","box":"empires","event":true,"cost":"0d8","requires":["Debt Tokens"]},// costs 0 coins, 8 debt
{"id":"Ritual","box":"empires","event":true,"cost":"4","requires":["VP tokens"]},
{"id":"Salt the Earth","box":"empires","event":true,"cost":"4","requires":["VP tokens"]},
{"id":"Tax","box":"empires","event":true,"cost":"2","requires":["Debt Tokens"]},
{"id":"Triumph","box":"empires","event":true,"cost":"0d5","requires":["Debt Tokens","VP tokens"]},// costs 0 coins, 5 debt
{"id":"Wedding","box":"empires","event":true,"cost":"4d3","requires":["Debt Tokens","VP tokens"]},// costs 4 coins, 3 debt
{"id":"Windfall","box":"empires","event":true,"cost":"5"},
{"id":"Aqueduct","box":"empires","type":"Landmark","event":true,"requires":["VP tokens"]},
{"id":"Arena","box":"empires","type":"Landmark","event":true,"requires":["VP tokens"]},
{"id":"Bandit Fort","box":"empires","type":"Landmark","event":true},
{"id":"Basilica","box":"empires","type":"Landmark","event":true,"requires":["VP tokens"]},
{"id":"Baths","box":"empires","type":"Landmark","event":true,"requires":["VP tokens"]},
{"id":"Battlefield","box":"empires","type":"Landmark","event":true,"requires":["VP tokens"]},
{"id":"Colonnade","box":"empires","type":"Landmark","event":true,"requires":["VP tokens"]},
{"id":"Defiled Shrine","box":"empires","type":"Landmark","event":true,"requires":["VP tokens"]},
{"id":"Fountain","box":"empires","type":"Landmark","event":true},
{"id":"Keep","box":"empires","type":"Landmark","event":true},
{"id":"Labyrinth","box":"empires","type":"Landmark","event":true,"requires":["VP tokens"]},
{"id":"Mountain Pass","box":"empires","type":"Landmark","event":true,"requires":["Debt Tokens","VP tokens"]},
{"id":"Museum","box":"empires","type":"Landmark","event":true},
{"id":"Obelisk","box":"empires","type":"Landmark","event":true},
{"id":"Orchard","box":"empires","type":"Landmark","event":true},
{"id":"Palace","box":"empires","type":"Landmark","event":true},
{"id":"Tomb","box":"empires","type":"Landmark","event":true,"requires":["VP tokens"]},
{"id":"Tower","box":"empires","type":"Landmark","event":true},
{"id":"Triumphal Arch","box":"empires","type":"Landmark","event":true},
{"id":"Wall","box":"empires","type":"Landmark","event":true},
{"id":"Wolf Den","box":"empires","type":"Landmark","event":true},
{"id":"Bard","box":"nocturne","type":"Action,Fate","cost":"4"},
{"id":"Blessed Village","box":"nocturne","type":"Action,Fate","cost":"4"},
{"id":"Changeling","box":"nocturne","type":"Night","cost":"3"},
{"id":"Cobbler","box":"nocturne","type":"Night,Duration","cost":"4"},
{"id":"Conclave","box":"nocturne","type":"Action","cost":"4"},
{"id":"Crypt","box":"nocturne","type":"Night,Duration","cost":"5"},
{"id":"Cursed Village","box":"nocturne","type":"Action,Doom","cost":"5"},
{"id":"Den of Sin","box":"nocturne","type":"Night,Duration","cost":"5"},
{"id":"Devil's Workshop","box":"nocturne","type":"Night","cost":"4","requires":["Imp"]},
{"id":"Druid","box":"nocturne","type":"Action,Fate","cost":"2"},
{"id":"Exorcist","box":"nocturne","type":"Night","cost":"4","requires":["Ghost","Imp","Will-o'-Wisp"]},
{"id":"Faithful Hound","box":"nocturne","type":"Action,Reaction","cost":"2"},
{"id":"Fool","box":"nocturne","type":"Action,Fate","cost":"3","requires":["Lucky Coin","States"]},
{"id":"Ghost Town","box":"nocturne","type":"Night,Duration","cost":"3"},
{"id":"Guardian","box":"nocturne","type":"Night,Duration","cost":"2"},
{"id":"Idol","box":"nocturne","type":"Treasure,Attack,Fate","cost":"5"},
{"id":"Leprechaun","box":"nocturne","type":"Action,Doom","cost":"3","requires":["Wish"]},
{"id":"Monastery","box":"nocturne","type":"Night","cost":"2"},
{"id":"Necromancer","box":"nocturne","type":"Action","cost":"4","requires":["Zombies"]},
{"id":"Night Watchman","box":"nocturne","type":"Night","cost":"3"},
{"id":"Pixie","box":"nocturne","type":"Action,Fate","cost":"2","requires":["Goat"]},
{"id":"Pooka","box":"nocturne","type":"Action","cost":"5","requires":["Cursed Gold"]},
{"id":"Raider","box":"nocturne","type":"Night,Duration,Attack","cost":"6"},
{"id":"Sacred Grove","box":"nocturne","type":"Action,Fate","cost":"5"},
{"id":"Secret Cave","box":"nocturne","type":"Action,Duration","cost":"3","requires":["Magic Lamp","Wish"]},
{"id":"Shepherd","box":"nocturne","type":"Action","cost":"4","requires":["Pasture"]},
{"id":"Skulk","box":"nocturne","type":"Action,Attack,Doom","cost":"4"},
{"id":"Tormentor","box":"nocturne","type":"Action,Attack,Doom","cost":"5","requires":["Imp"]},
{"id":"Tragic Hero","box":"nocturne","type":"Action","cost":"5"},
{"id":"Tracker","box":"nocturne","type":"Action,Fate","cost":"2","requires":["Pouch"]},
{"id":"Vampire","box":"nocturne","type":"Night,Attack,Doom","cost":"5","requires":["Bat"]},
{"id":"Werewolf","box":"nocturne","type":"Action,Night,Attack,Doom","cost":"5"},
{"id":"Cemetery","box":"nocturne","type":"Victory","cost":"4","requires":["Ghost","Haunted Mirror"]},
{"id":"The Earth's Gift","box":"nocturne","type":"Boon","special":true},
{"id":"The Field's Gift","box":"nocturne","type":"Boon","special":true},
{"id":"The Flame's Gift","box":"nocturne","type":"Boon","special":true},
{"id":"The Forest's Gift","box":"nocturne","type":"Boon","special":true},
{"id":"The Moon's Gift","box":"nocturne","type":"Boon","special":true},
{"id":"The Mountain's Gift","box":"nocturne","type":"Boon","special":true},
{"id":"The River's Gift","box":"nocturne","type":"Boon","special":true},
{"id":"The Sea's Gift","box":"nocturne","type":"Boon","special":true},
{"id":"The Sky's Gift","box":"nocturne","type":"Boon","special":true},
{"id":"The Sun's Gift","box":"nocturne","type":"Boon","special":true},
{"id":"The Swamp's Gift","box":"nocturne","type":"Boon","requires":["Will-o'-Wisp"],"special":true},
{"id":"The Wind's Gift","box":"nocturne","type":"Boon","special":true},
{"id":"Bat","box":"nocturne","type":"Night,Special","cost":"2","special":true},
{"id":"Boons","box":"nocturne","special":true},
{"id":"Cursed Gold","box":"nocturne","type":"Treasure,Heirloom,Special","cost":"4","special":true},
{"id":"Goat","box":"nocturne","type":"Treasure,Heirloom,Special","cost":"2","special":true},
{"id":"Ghost","box":"nocturne","type":"Night,Duration,Spirit,Special","cost":"4","special":true},
{"id":"Imp","box":"nocturne","type":"Action,Spirit,Special","cost":"2","special":true},
{"id":"Haunted Mirror","box":"nocturne","type":"Treasure,Heirloom,Special","cost":"0","special":true},
{"id":"Hexes","box":"nocturne","special":true},
{"id":"Lucky Coin","box":"nocturne","type":"Treasure,Heirloom,Special","cost":"4","special":true},
{"id":"Magic Lamp","box":"nocturne","type":"Treasure,Heirloom,Special","cost":"0","special":true},
{"id":"Pasture","box":"nocturne","type":"Treasure,Victory,Heirloom,Special","cost":"2","special":true},
{"id":"Pouch","box":"nocturne","type":"Treasure,Heirloom,Special","cost":"2","special":true},
{"id":"States","box":"nocturne","special":true},
{"id":"Will-o'-Wisp","box":"nocturne","type":"Action,Spirit,Special","cost":"0","special":true},
{"id":"Wish","box":"nocturne","type":"Action,Special","cost":"0","special":true},
{"id":"Zombies","box":"nocturne","special":true}//,
],
"boxes":[
{"id":"base","name":"Base","image":"Dominion.jpg","icon_image":"20px-Dominion_icon.png"},
{"id":"intrigue","name":"Intrigue","image":"Intrigue.jpg","icon_image":"20px-Intrigue_icon.png"},
{"id":"seaside","name":"Seaside","image":"Seaside.jpg","icon_image":"16px-Seaside_icon.png"},
{"id":"alchemy","name":"Alchemy","image":"Alchemy.jpg","icon_image":"12px-Alchemy_icon.png"},
{"id":"prosperity","name":"Prosperity","image":"Prosperity.jpg","icon_image":"20px-Prosperity_icon.png"},
{"id":"cornucopia","name":"Cornucopia","image":"Cornucopia.jpg","icon_image":"19px-Cornucopia_icon.png"},
{"id":"hinterlands","name":"Hinterlands","image":"299px-Hinterlands.jpg","icon_image":"20px-Hinterlands_icon.png"},
{"id":"darkages","name":"Dark Ages","image":"300px-Dark_Ages.jpg","icon_image":"17px-Dark_Ages_icon.png"},
{"id":"guilds","name":"Guilds","image":"Guilds.jpg","icon_image":"17px-Guilds_icon.png"},
{"id":"adventures","name":"Adventures","image":"Adventures.jpg","icon_image":"20px-adventures_icon.png"},
{"id":"empires","name":"Empires","image":"Empires.jpg","icon_image":"20px-Empires_icon.png"},
{"id":"nocturne","name":"Nocturne","image":"Nocturne.jpg","icon_image":"20px-Nocturne_icon.png"}//,
]
}
